### ISSUE TITLE
WE SHOULD STORE NOTHING BUT ACCELERATION

### ISSUE THREAD

**Issue by AvionicsPerson-CT** [USSTR-Avionics/Avionics_code#25]
We should store our x, y, and z acceleration (or our accelerations rate of change (called jerk apparently) which would be better I think) and use that to figure out our x, y, and z velocity as well as altitude and other things by assuming we start at 0 altitude and x, y, z velocity then use our moment to moment acceleration to figure out where we were during the flight with math.

**Comment by frroossst** [comment]
> Sometimes your genius is almost frightening

**Comment by djh293** [comment]
DISAGREE. WE SHOULD STORE NOTHING BUT ALTITUDE
