### ISSUE TITLE
Add ifndef to include statements

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Avionics_code#26]
To prevent possible errors in linkage

**Comment by snowy-shadow** [comment]
bro 💀 that's a lot of `ifndef`
could you elaborate what you mean by possible errors in linkage?

**Comment by frroossst** [comment]
With a big enough project, we might end up creating circular dependencies which will cause a linker error when trying to compile the program. And it is generally a good practice to avoid double `#include`s 

https://en.wikipedia.org/wiki/Include_guard#Double_inclusion

It's just good practice to keep everything fairly standard as the code will tend towards more entropy as it gets larger and we rush code.

And yes, that's a lot of ifndef, but we aren't doing anything until after the new year's

**Comment by frroossst** [comment]
Completed with commit master@5e7e394af271c8ed9ef26b151c73a38915443c32
