### ISSUE TITLE
Impl writing to FRAM

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Avionics_code#35]

**Comment by frroossst** [comment]
Store FRAM read and write cursors on the FRAM itself when they are updated. This allows us to not loose data or overwrite important data

**Comment by snowy-shadow** [comment]
we won't need to do that if we can figure out a good layout to store the data. e.g. with a value table stored on the fram or a preregistered address for each variable. I still have doubts on how your initially proposed solution of interweaving the data could work

**Comment by frroossst** [comment]
This was something I saw on the cubesat codebase and thought it was neat.  

Could you elaborate on what you mean by the interweaving data? If you're referring to the fancy way of trying to save space with floats then that wouldn't be a priority right now :)

**Comment by frroossst** [comment]
Initial code: https://github.com/USSTR-Avionics/Avionics_code/pull/51

**Comment by frroossst** [comment]
Code requires testing but everything is mainly there with this commit a5b916d6fb989be90598b35d11d0a04c3b80aae1
