### ISSUE TITLE
Test FRAM reads

### ISSUE THREAD

**Issue by frroossst** [USSTR-Avionics/Avionics_code#62]
Fram reading mode seems to reset

- Write unit tests for fram data chunk read/ write
- Check if read and write work as expected
- Debug

**Comment by EricC1231** [comment]
data writes correctly up to 9
after 10, starts overwriting 1
starts writing data incorrectly
error grows faster than correct data
might have integer overflow

**Comment by frroossst** [comment]
Possibly fixed with #67
